version: "3.8"

services: 

    application:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: 
            - ./.env
        ports: 
            - 80:${APP_PORT}
        restart: always
        links: 
            - mysql

    mysql:
        image: mysql:5.7
        volumes: 
            - ./tmp/mysql:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
